### ISSUE TITLE
节点缺失

### ISSUE THREAD

**Issue by Nanyuting** [xiwan/comfyUI-workflows#1]
似乎LoopStart_LATENT和LoopEnd_LATENT缺失，在网上都找不到。是我打开方式的错误吗？
![缺失节点](https://github.com/xiwan/comfyUI-workflows/assets/112244407/61210e13-d0e0-4d6e-98c0-2b1c0df60139)

**Comment by xiwan** [comment]
sorry，这个是我自己写的plugin，晚点我发下

**Comment by Nanyuting** [comment]
辛苦，感谢
